# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="steeef"

# Example aliases
alias zshconfig="vi ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# for virtualenvwrapper
export WORKON_HOME="$HOME/Envs"
export PROJECT_HOME="$HOME/Devel"
export DISABLE_VENV_CD=1

# for golang
export GOROOT="/gentoo/usr/lib/go"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
	git
	osx
	python
	git-flow
	github
	golang
	pip
	svn
	vi-mode
	virtualenvwrapper
	gentoo-prefix
	)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

alias ping='/sbin/ping'
alias lish="ssh -t hongqn@lish-atlanta.linode.com matariel"
alias svn="/gentoo/usr/bin/svn"
alias pydoc="python -m pydoc"
alias code='/Users/hongqn/Envs/codecli/bin/code'
mplayer_cli="/Applications/MPlayer OSX.app/Contents/Resources/External_Binaries/mplayer_intel.app/Contents/MacOS/mplayer"
[ -e "$mplayer_cli" ] && alias mplayer="\"$mplayer_cli\""

export PATH=$HOME/bin:$HOME/.local/bin:$PATH:/sbin:/usr/sbin:/usr/local/bin
export VISUAL=vi
export LC_ALL="en_US.UTF-8"

bindkey '^R' history-incremental-search-backward
